### ISSUE TITLE
(Sosnowiec Glowny) Trains 24xxx & 42xxx are not displayed under "Online"

### ISSUE THREAD

**Issue by TheFloxiCz** [DKFN/edr-issues#30]
Hi, I noticed that trains with numbers 24xxx and 42xxx from Sosnowiec Poludniowy are not displayed in the category "online" trains, even when they already passing the station (SG pzs. R52). Everytime I have to refresh the page to see them in the list. They are spawned ~6 minutes before driving through SG pzs. R52.
Direction from Katowice seems to work without problems.

**Comment by DKFN** [comment]
Hey thanks for reporting the issue.
I will need to wait until this evening to investigate. It is probably also related to this issue #31 
Thanks !

**Comment by DKFN** [comment]
I realized its probably not related to #31 but instead its #15 (again in french sorry this is an old issue of 2days). Its quite hard to check for the bug fixing since trains take time to be online/offline.

I have tried to fix it on 0.4 but it did not have worked so I'll probably have to refactor the code for this part a bit more.

It is on my top priority list at the moment and will be included in the next release.

Thanks !

**Comment by Iwhite67** [comment]
The problem is due because this train spawn only when sosno polu ask to glowny if he can send a train

**Comment by DKFN** [comment]
Indeed, I actually made it worse :sweat_smile: I need to cross merge both posts. I added a "Primary post" and "Secondary posts" in order to make the display of Sosnowiec better.
The problem is that some are only in one post, orther trains in the orther post. So I need to make it a bit better.
I should have a little fix during luch tiime, hopefully :)

**Comment by DKFN** [comment]
Thank you very much @Iwhite67 and @TheFloxiCz the issue should now be fixed ! :)
**Please note that it will take up to 4hours for the posts data to update** 

Thanks for reporting !

**Comment by DKFN** [comment]
Thanks all, released of v0.5 ! :)
